name: Trigger Workflow in Another Repository

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in Repository B
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/Prakhar10747884/repoB/dispatches \
            -d '{"event_type":"custom_event"}'
